/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcm_lib_DevMain */

#ifndef _Included_com_mcm_lib_DevMain
#define _Included_com_mcm_lib_DevMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcm_lib_DevMain
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mcm_lib_DevMain_main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
